#!/bin/bash

#+--------------------------------------------------------------------------------+
#| Version : V0.2                                                                 |
#| Description : Script chat / d'aide pour communiquer avec les joueurs
#| Auteur : CESI MSSI 2019 [Maxence Serment]                                      |
#| Date : 25-07-20                                                                |
#|                                                                                |
#+--------------------------------------------------------------------------------+
#~

source $ESCAPE_UTIL

function main()
{
	init
}

function init()
{
	e_header "CHAT / AIDE"
	echo $(e_warning2 "") "Tapez ${bold}'?'${reset} puis 'ENTRER' puis posez votre question" 
	echo
	echo $(tty) > /tmp/TTY_JOUEURS
	bash
}



main
