#!/bin/bash

#+--------------------------------------------------------------------------------+
#| Version : V0.1                                                                 |
#| Description : Script de cron qui s'occupe du redémarrage                       |
#|				des scripts si fermés par erreur                                  |
#|
#| Auteur : CESI MSSI 2019 [Maxence Serment]                                      |
#| Date : 10-06-20                                                                |
#+--------------------------------------------------------------------------------+
#~

resize -s 10 40

#srcDir=/home/mserment/Documents/mdnotes/perso/escape/scripts/src
srcDir=/home/kali/escape/src

#export ESCAPE_UTIL=/home/mserment/Documents/mdnotes/perso/escape/scripts/res/escape_f_utils
export ESCAPE_UTIL=/home/kali/escape/res/escape_f_utils
source $ESCAPE_UTIL

while true
do
	clear
	e_header "CRONTAB CHECK"
	e_header "CRONTAB CHECK"
    echo "            - $(date +%H:%M:%S) -"
    echo "            - $(date +%H:%M:%S) -" >> $(cat /tmp/TTY_CRON)
	echo
	echo >> $(cat /tmp/TTY_CRON)

	hackerScript=`/bin/ps -fu $USER| grep "boot" | grep -v "grep" | awk '{print $2}'`
	echo "$(e_warning "boot  PID : ") ${bold}$hackerScript ${reset}"
	echo "$(e_warning "boot  PID : ") ${bold}$hackerScript ${reset}" >> $(cat /tmp/TTY_CRON)

	timerScript=`/bin/ps -fu $USER| grep "timer" | grep -v "grep" | awk '{print $2}'`
	echo "$(e_warning "timer PID : ") ${bold}$timerScript ${reset}"
	echo "$(e_warning "timer PID : ") ${bold}$timerScript ${reset}" >> $(cat /tmp/TTY_CRON)

	chatScript=`/bin/ps -fu $USER| grep "chat" | grep -v "grep" | awk '{print $2}'`
	echo "$(e_warning "chat  PID : ") ${bold}$chatScript ${reset}"
	echo "$(e_warning "chat  PID : ") ${bold}$chatScript ${reset}" >> $(cat /tmp/TTY_CRON)
	echo;echo
	echo >> $(cat /tmp/TTY_CRON);echo >> $(cat /tmp/TTY_CRON)
	echo "${bold}=====================================${reset}"
	echo "${bold}=====================================${reset}" >> $(cat /tmp/TTY_CRON)



	if [ -e $hackerScript ]; then 
		#lancement de la simulation 
		#bash -c "gnome-terminal -- $srcDir/boot" & 
		pkill boot
		bash -c "xfce4-terminal --geometry +0+0 --hide-menubar --hide-toolbar --hide-scrollbar --title=\"HACKER PC\" -x $ESCAPE_SRC/boot" & 
	fi

	if [ -e $timerScript ]; then 
		#lancement du timer 
		#bash -c "gnome-terminal -- $srcDir/timer" & 
		pkill timer
		bash -c "xfce4-terminal --geometry +1400+20 --hide-menubar --hide-toolbar --hide-scrollbar --title=TIMER -x $ESCAPE_SRC/timer" & 
	fi

	if [ -e $chatScript ]; then 
		#lancement du chat 
		#bash -c "gnome-terminal -- $srcDir/timer" & 
		pkill chat
		bash -c "xfce4-terminal --geometry 60x30+1400+550 --hide-menubar --hide-toolbar --hide-scrollbar --title=\"CHAT / AIDE\" -x $ESCAPE_SRC/chat" & 
	fi
	sleep 1
done
