#!/bin/bash
while true; do
	clear
    echo "#################################################################"
    echo "#                       __ ATTENTION __                         #"
    echo "#                                                               #"
    echo "#              LA SESSION EST ARRIVEE A EXPIRATION              #"
    echo "#              TOUS LES FICHIERS ONT ETE SUPPRIMES              #"
    echo "#                         AUREVOIR  :)                          #"
    echo "#                                                               #"
    echo "#################################################################"
    sleep 10
done