#!/bin/bash

#+--------------------------------------------------------------------------------+
#| Version : V0.1                                                                 |
#| Description : Script de simulation de connexion SSH                            |
#| Auteur : CESI MSSI 2019 [Maxence Serment]                                      |
#| Date : 27-05-20                                                                |
#+--------------------------------------------------------------------------------+
#~

source $ESCAPE_UTIL

password1=defaultpass1!
password2=defaultpass2!
password3=defaultpass3!


function main()
{
	hackerName=$(read_settings hackerName)	
	password1=$(read_settings pass_xp)	
	password2=$(read_settings pass_caviar)	
	password3=$(read_settings pass_bourgeau)	
	menu_connexiond
}

function menu_connexiond
{

	clear
	e_header "CONNEXION A DISTANCE"
	echo "1: [WINDOWS XP]        : 10.2.145.29" 
	echo "2: [POSTE DE CAVIAR]   : 10.2.145.114"
	echo "3: [POSTE DE BOURGEAU] : 10.2.145.155"
	echo
	echo "q: Quitter cet ecran et revenir au precedent"
	echo "======================================"
	echo -n "Faites un choix : "
	read choix
	
	if [ "$choix" == "1" ] ; then
		connexionServeur "10.2.114.29 - WINDOWS XP"
	elif [ "$choix" == "2" ] ; then
		connexionServeur "10.2.145.114 - POSTE DE CAVIAR"
	elif [ "$choix" == "3" ] ; then
		connexionServeur "10.2.145.155 - POSTE DE BOURGEAU"
	elif [ "$choix" == "q" ] ; then
		if [ "$win" == "true" ]; then
			pkill -STOP timer # Freeze le timer 
			eog $ESCAPE_RES/img/win/mail_transaction.png &
			sleep 1
			eog $ESCAPE_RES/img/win/transaction.png &
			bash -c "xfce4-terminal --geometry 56x16+700+500 --hide-borders --hide-menubar --hide-toolbar --hide-scrollbar -x $ESCAPE_SRC/win" &
		fi
		$ESCAPE_SRC/m_principal
	else
		echo
		echo -n $(e_warning "Veuillez selectionner un des choix du menu ")
		sleep $ESCAPE_SLEEPTIME_M
		menu_connexiond
	fi
}

# Simulation de connexion a distance
function connexionServeur()
{

	clear
	e_header "CONNEXION A DISTANCE"
	echo "Connexion a la machine $1 ..."
	sleep $ESCAPE_SLEEPTIME_M
	echo
	echo "Attention : "${tan}$(e_flash "Un mot de passe")" est necessaire pour cette connexion"
	user_confirmation "Voulez vous continuer ?"
	if is_confirmed; then 
		e_warning "Entrez 'q' pour quitter cet ecran et revenir au precedent"
		echo
		motDePasse $1
	else 
		echo
		echo -n "Retour au menu des connexion ..."
		sleep $ESCAPE_SLEEPTIME_M
	 	menu_connexiond
	 fi

}

function motDePasse()
{
	password=
	if [ "$1" == "10.2.114.29" ] ; then password=$password1; fi
	if [ "$1" == "10.2.145.114" ] ; then password=$password2; fi
	if [ "$1" == "10.2.145.155" ] ; then password=$password3; fi

	echo -n "Mot de passe : "
	read choix
	
	if [ "$choix" == "$password" ] ; then
		#Password is valid !	
		e_success "Le mot de passe est valide !"
		e_warning2 "Connexion a la machine ..."

		# Connexion 10.2.114.29  : XP
		if [ "$1" == "10.2.114.29" ] ; then 
			sleep $ESCAPE_SLEEPTIME_M
			echo "- Affichage des plans 1 & 2 ..."
			eog $ESCAPE_RES/img/connexion_distance/xp/content/planMaisonProt1.png & 
			sleep 0.5
			eog $ESCAPE_RES/img/connexion_distance/xp/content/planMaisonProt2.png &
			sleep 0.5
			echo "- Affichage des etudes thermiques"
			eog $ESCAPE_RES/img/connexion_distance/xp/content/calcul_thermique.png & 
			sleep 0.5
			eog $ESCAPE_RES/img/connexion_distance/xp/content/echange_thermique.jpg &
			sleep 0.5
			echo "- Affichage de la decoupe du mur"
			eog $ESCAPE_RES/img/connexion_distance/xp/content/decoupe_mur.png & 
			sleep 0.5
			echo "- Affichage du descriptif de la maison"
			eog $ESCAPE_RES/img/connexion_distance/xp/content/descriptif_maison.jpg & 
			sleep 0.5
			echo "- Affichage draft slide presentation nouveau produit"
			eog $ESCAPE_RES/img/connexion_distance/xp/content/presentation_nouveau_produit.png &

			echo
			user_wait_input "Appuyez sur [ENTREE] pour revenir au menu precedent"
			eog $ESCAPE_RES/img/connexion_distance/xp/sortie/email_client_final.png & 
			sleep 1
			eog $ESCAPE_RES/img/connexion_distance/xp/sortie/39_journal_7.jpg &
			echo "7;39 Journal 7;$ESCAPE_RES/img/journaux/39_journal_7/39_journal_7.jpg" >> /tmp/journaux
			export win=true
			menu_connexiond

		fi
		# Connexion 10.2.145.114 : POSTE DE CAVIAR
		if [ "$1" == "10.2.145.114" ] ; then 
			sleep $ESCAPE_SLEEPTIME_M

			sleep 0.2
			echo "- Calendrier ELiot ALLARD"
			eog $ESCAPE_RES/img/connexion_distance/caviar/1/calendrier-Eliot.png &
			sleep 0.2
			echo "- Carte visite restaurant"
			eog $ESCAPE_RES/img/connexion_distance/caviar/1/CarteVisiteRestaurant.png & 

			user_wait_input "Appuyez sur [ENTREE] pour continuer"
			echo "- Affichage journal #3_2"
			eog $ESCAPE_RES/img/connexion_distance/caviar/journal/21_journal_3_2.jpg & 
			echo "5;21 Journal 3.2;$ESCAPE_RES/img/journaux/21_journal_3_2/21_journal_3_2.png" >> /tmp/journaux

			user_wait_input "Appuyez sur [ENTREE] pour continuer ..."

			sleep 0.2
			echo "- Note de la secretaire"
			eog $ESCAPE_RES/img/connexion_distance/caviar/2/24_note_secretaire.jpg & 

			echo
			user_wait_input "Appuyez sur [ENTREE] pour revenir au menu precedent"; if is_confirmed; then menu_connexiond; fi 
			menu_connexiond

		fi
		# Connexion 10.2.145.155 : POSTE DE BOURGEAU
		if [ "$1" == "10.2.145.155" ] ; then 
			chars="/-\|"
			echo
			for i in {1..5}
			 do
						for (( i=0; i<${#chars}; i++ )); do
							sleep 0.1
							echo -en "${chars:$i:1}" "\r"
						done
			done
			echo;echo
			e_success "Connexion a la machine OK !"
			e_warning2 "Connexion au reseau de management ..."
			echo
			for i in {1..10}
			 do
						for (( i=0; i<${#chars}; i++ )); do
							sleep 0.1
							echo -en "${chars:$i:1}" "\r"
						done
			done
			echo ""
			echo "$(e_error "Echec de connexion : ${bold}${red}${flashred}Connexion refusee !${reset}")" # echec normal
			echo "$(e_error "Acces a distance ${bold}impossible ${reset}...")"
			echo "$(e_error "Multi Authentification requise...")"
			eog $ESCAPE_RES/img/connexion_distance/bourgeau/content/2fa.png &

			sleep $ESCAPE_SLEEPTIME_L

			user_wait_input "Appuyez sur [ENTREE] pour revenir au menu precedent"; if is_confirmed; then menu_connexiond; fi
			eog $ESCAPE_RES/img/connexion_distance/bourgeau/sortie/31_photo_mariage_2.png &
			sleep 1
			eog $ESCAPE_RES/img/connexion_distance/bourgeau/sortie/30_journal_5.png &
			echo "6;30 Journal 5;$ESCAPE_RES/img/journaux/30_journal_5/30_journal_5.png" >> /tmp/journaux
			menu_connexiond
		fi


	elif [ "$choix" == "q" ] ; then
		menu_connexiond
	else
		e_error "Erreur : Le mot de passe est incorrect"
		sleep $ESCAPE_SLEEPTIME_M
		motDePasse $1
	fi


}

main
