#!/bin/bash

#+--------------------------------------------------------------------------------+
#| Version : V0.1                                                                 |
#| Description : Script de simulation de connexion SSH                            |
#| Auteur : CESI MSSI 2019 [Maxence Serment]                                      |
#| Date : 27-05-20                                                                |
#+--------------------------------------------------------------------------------+
#~

source $ESCAPE_UTIL

password1=defaultpass1!
password2=defaultpass2!
password3=defaultpass3!


function main()
{
	hackerName=$(read_settings hackerName)	
	password1=$(read_settings pass_xp)	
	password2=$(read_settings pass_caviar)	
	password3=$(read_settings pass_bourgeau)	
	menu_connexiond
}

function menu_connexiond
{

	clear
	e_header "CONNEXION A DISTANCE"
	echo "1: [WINDOWS XP]        : 10.2.145.29" 
	echo "2: [POSTE DE CAVIAR]   : 10.2.145.114"
	echo "3: [POSTE DE BOURGEAU] : 10.2.145.155"
	echo
	echo "q: Quitter cet ecran et revenir au precedent"
	echo "======================================"
	echo -n "Faites un choix : "
	read choix
	
	if [ "$choix" == "1" ] ; then
		connexionServeur "10.2.114.29 - WINDOWS XP"
	elif [ "$choix" == "2" ] ; then
		connexionServeur "10.2.145.114 - POSTE DE CAVIAR"
	elif [ "$choix" == "3" ] ; then
		connexionServeur "10.2.145.155 - POSTE DE BOURGEAU"
	elif [ "$choix" == "q" ] ; then
		$ESCAPE_SRC/m_principal
	else
		echo
		echo -n $(e_warning "Veuillez selectionner un des choix du menu ")
		sleep $ESCAPE_SLEEPTIME_M
		menu_connexiond
	fi
}

# Simulation de connexion a distance
function connexionServeur()
{

	clear
	e_header "CONNEXION A DISTANCE"
	echo "Connexion au serveur $1 ..."
	sleep $ESCAPE_SLEEPTIME_M
	echo
	echo "Attention : "${tan}$(e_flash "Un mot de passe")" est nécéssaire pour cette connexion"
	user_confirmation "Voulez vous continuer ?"
	if is_confirmed; then 
		e_warning "Entrez 'q' pour quitter cet ecran et revenir au precedent"
		echo
		motDePasse $1
	else 
		echo
		echo -n "Retour au menu des connexion ..."
		sleep $ESCAPE_SLEEPTIME_M
	 	menu_connexiond
	 fi

}

function motDePasse()
{
	password=
	if [ "$1" == "10.2.114.29" ] ; then password=$password1; fi
	if [ "$1" == "10.2.145.114" ] ; then password=$password2; fi
	if [ "$1" == "10.2.145.155" ] ; then password=$password3; fi

	echo -n "Mot de passe : "
	read choix
	
	if [ "$choix" == "$password" ] ; then
		#Password is valid !	
		e_success "Le mot de passe est valide !"
		e_warning2 "Connexion au serveur ..."

		# Connexion 10.2.114.29  : XP
		if [ "$1" == "10.2.114.29" ] ; then 
			sleep $ESCAPE_SLEEPTIME_M
			echo "- Affichage des prototypes 1 & 2 ..."
			eog $ESCAPE_RES/planMaisonProt1.png & 
			sleep 0.5
			eog $ESCAPE_RES/planMaisonProt2.png &
			echo "- Message reçu : Mission accomplie ..." # fin de l'escape game 
			eog $ESCAPE_RES/textDeFeliciations4.gif &
			echo
			user_wait_input "Appuyez sur [ENTREE] pour revenir au menu precedent"; if is_confirmed; then menu_connexiond; fi 
			menu_connexiond

		fi
		# Connexion 10.2.145.114 : POSTE DE CAVIAR
		if [ "$1" == "10.2.145.114" ] ; then 
			sleep $ESCAPE_SLEEPTIME_M

			sleep 0.2
			echo "- Calendrier ELiot ALLARD"
			eog $ESCAPE_RES/calendrier-Eliot.png &
			sleep 0.2
			echo "- Carte visite restaurant"
			eog $ESCAPE_RES/CarteVisiteRestaurant.png & 

			user_wait_input "Appuyez sur [ENTREE] pour continuer ..."; if is_confirmed; then menu_connexiond; fi 

			sleep 0.2
			echo "- Note de la secretaire"
			eog $ESCAPE_RES/24_note_du_secretaire.png & 

			echo
			user_wait_input "Appuyez sur [ENTREE] pour revenir au menu precedent"; if is_confirmed; then menu_connexiond; fi 
			menu_connexiond

		fi
		# Connexion 10.2.145.155 : POSTE DE BOURGEAU
		if [ "$1" == "10.2.145.155" ] ; then 
			chars="/-\|"
			echo
			for i in {1..20}
			 do
						for (( i=0; i<${#chars}; i++ )); do
							sleep 0.1
							echo -en "${chars:$i:1}" "\r"
						done
			done
			echo;echo
			echo "$(e_error "Echec de connexion : ${bold}${red}${flashred}Connexion refusée !${reset}")" # echec normal
			echo "$(e_error "Acces a distance ${bold}impossible ${reset}...")"
			sleep $ESCAPE_SLEEPTIME_L

			user_wait_input "Appuyez sur [ENTREE] pour revenir au menu precedent"; if is_confirmed; then menu_connexiond; fi 
			menu_connexiond
		fi


	elif [ "$choix" == "q" ] ; then
		menu_connexiond
	else
		e_error "Erreur : Le mot de passe est incorrect"
		sleep $ESCAPE_SLEEPTIME_M
		motDePasse $1
	fi


}

main
