#!/bin/bash

#+--------------------------------------------------------------------------------+
#| Version : V0.1                                                                 |
#| Description : Script d'affichage des pages de journal de la hackeuse           |
#| Auteur : CESI MSSI 2019 [Maxence Serment]                                      |
#| Date : 27-05-20                                                                |
#+--------------------------------------------------------------------------------+
#~

source $ESCAPE_UTIL

listeJournaux=$ESCAPE_RES/journal_list.txt

function main()
{
	menu_journal
}


# Affichage de la liste des journaux
function menu_journal()
{
	clear
	e_header "JOURNAUX"
	listeJournaux=/tmp/journaux
	echo
	if [ ! -f $listeJournaux ]; then
		echo  -e "Aucune Entree de journal n'a ete debloquee"
		echo
		echo "Appuyer sur [ Entrer ] pour revenir au menu precedent"
		read
		$ESCAPE_SRC/m_principal
	fi
	for line in $(sort /tmp/journaux); do
		number=$(echo $line | awk -F ";" '{ print $1}')
		name=$(echo $line | awk -F ";" '{ print $2}')
		echo "$number  -  $name"
	done
	echo "================================="
	echo
	echo "q: Quitter cet ecran et revenir au precedent"
	echo
	echo -n "Faites un choix : "
	read choix
	

	for line in $(sort /tmp/journaux); do
		number=$(echo $line | awk -F ";" '{ print $1}')
		name=$(echo $line | awk -F ";" '{ print $2}')
		path=$(echo $line | awk -F ";" '{ print $3}')
		if [ "$number" == "$choix" ]; then
			echo "$(Affichage de $name)"
			eog $path &
			menu_journal
		fi
	done

	if [ "$choix" == "q" ]; then
		$ESCAPE_SRC/m_principal
	elif [ "$choix" == "Q" ]; then
		$ESCAPE_SRC/m_principal
	else
		echo
		echo -n $(e_warning "Veuillez selectionner un des choix du menu. [chiffre de 1 a 5]")
		sleep $ESCAPE_SLEEPTIME_M
		menu_journal
	fi
}


function affichagePage()
{

	numero=$1 #numero de la page a afficher

	clear
	e_header "AFFICHAGE DE LA PAGE #$numero"
	echo 
	# Affiche la page
	if [ $numero == "1" ]; then nomFichier=$ESCAPE_RES/journal_1.txt; fi
	if [ $numero == "2" ]; then nomFichier=$ESCAPE_RES/journal_2.txt; fi
	if [ $numero == "3" ]; then nomFichier=$ESCAPE_RES/journal_3.txt; fi
	if [ $numero == "4" ]; then nomFichier=$ESCAPE_RES/journal_4.txt; fi
	if [ $numero == "5" ]; then nomFichier=$ESCAPE_RES/journal_5.txt; fi

	cat $nomFichier
	echo "==========================================="
	echo
	user_wait_input "Appuyez sur une touche pour revenir au menu precedent"; if is_confirmed; then menu_reception; fi 
	menu_journal
}

main
