#!/bin/bash

#+--------------------------------------------------------------------------------+
#| Version : V0.1                                                                 |
#| Description : Script de simulation d'un fichier maltego                        |
#| Auteur : CESI MSSI 2019 [Maxence Serment]                                      |
#| Date : 27-05-20                                                                |
#+--------------------------------------------------------------------------------+
#~

source $ESCAPE_UTIL

function main()
{
	e_warning2 "Lancement de l'interface maltego ..."
	sleep 1
	menu_maltego
}

function menu_maltego
{
	echo ""
	eog $ESCAPE_RES/img/maltego/extract_maltego.png & 
	sleep 0.5
	eog $ESCAPE_RES/img/maltego/journal/19_journal_2_1.png &
	sleep 0.5
	user_wait_input "Appuyez sur une touche pour revenir au menu precedent"; if is_confirmed; then $ESCAPE_SRC/m_principal; fi 
	$ESCAPE_SRC/m_principal
}

main
