#!/bin/bash

#+--------------------------------------------------------------------------------+
#| Version : V0.1                                                                 |
#| Description : Script de simulation d'une boite mail                            |
#| Auteur : CESI MSSI 2019 [Maxence Serment]                                      |
#| Date : 27-05-20                                                                |
#+--------------------------------------------------------------------------------+
#~

source $ESCAPE_UTIL

listeMail_reception=$ESCAPE_RES/mail_reception_list.txt
listeMail_envois=$ESCAPE_RES/mail_envois_list.txt


function main()
{
	#e_warning2 "lancement de l'interface de mail "
	#sleep $ESCAPE_SLEEPTIME_M 
	#menu_mail # plus besoin si uniquement la boite de reception
	
	#if [ "$ESCAPE_EXPORTVAR_MAIL" == "" ]; then 
		#echo "- Affichage des pages du journal #2"
		#eog $ESCAPE_RES/img/mailjournal/19_journal_2_3.png &
		#sleep 0.5
		#eog $ESCAPE_RES/img/mailjournal/19_journal_2_2.png &
		#sleep 0.5
		#eog $ESCAPE_RES/img/mailjournal/19_journal_2_1.png &
		#user_wait_input "Appuyez sur ${bold}[ENTRER]${reset}pour continuer"; if is_confirmed; then menu_reception; fi 
		#export ESCAPE_EXPORTVAR_MAIL=1
	#fi

	menu_mail
	#menu_reception
}

function menu_mail()
{
	clear
	e_header "BOITE MAIL"
	echo "1: Boite de reception"
	echo "2: Boite d'envois"
	echo
	echo "q: Quitter cet ecran et revenir au precedent"
	echo "======================================"
	echo -n "Faites un choix : "
	read choix
	
	if [ "$choix" == "1" ] ; then
		menu_reception
	elif [ "$choix" == "2" ] ; then
		menu_envois
	elif [ "$choix" == "q" ] ; then
		$ESCAPE_SRC/m_principal
	else
		echo
		echo -n $(e_warning "Veuillez selectionner un des choix du menu ")
		sleep $ESCAPE_SLEEPTIME_M
		menu_mail
	fi

}

function menu_reception()
{
	clear
	e_header "BOITE DE RECEPTION"
	# Affiche une liste de mail 
	cat $listeMail_reception
	echo "==========================================="
	echo
	echo "q: Quitter cet ecran et revenir au precedent"
	echo
	echo -n "Faites un choix : "
	read choix
	
	if [ "$choix" == "1" ] ; then
		affichageMail_reception 1
	elif [ "$choix" == "2" ] ; then
		affichageMail_reception 2
	elif [ "$choix" == "3" ] ; then
		affichageMail_reception 3
	elif [ "$choix" == "q" ] ; then
		menu_mail
		#$ESCAPE_SRC/m_principal

	else
		echo
		echo -n $(e_warning "Veuillez selectionner un des choix du menu. [chiffre de 1 a 3]")
		sleep $ESCAPE_SLEEPTIME_M
		menu_reception
	fi
}

function affichageMail_reception()
{
	numero=$1 #numero du mail a afficher

	clear
	e_header "AFFICHAGE DU MAIL #$numero"

	# Affiche le mail 
	if [ $numero == "1" ]; then nomFichier=$ESCAPE_RES/img/mail/reception/m1/17-email1.png; fi
	if [ $numero == "2" ]; then nomFichier=$ESCAPE_RES/img/mail/reception/m2/18-email2.png; fi
	if [ $numero == "3" ]; then nomFichier=$ESCAPE_RES/img/mail/reception/m3/19-email3.png; fi

	#cat $nomFichier
	eog $nomFichier &
	sleep 1
	if [ $numero == "1" ]; then
		eog $ESCAPE_RES/img/mail/reception/m1/journal/19_journal_2_2_2.png &
		echo "3;19_Journal_2.2.2;$ESCAPE_RES/img/journaux/19_journal_2_2_2/19_journal_2_2_2.png" >> /tmp/journaux
	fi
	echo "==========================================="
	echo
	user_wait_input "Appuyez sur une touche pour revenir au menu precedent"; if is_confirmed; then menu_reception; fi
	if [ $numero == "2" ]; then
		eog $ESCAPE_RES/img/mail/reception/m2/journal/19_journal_2_3.png &
		echo "4;19_Journal_2.3;$ESCAPE_RES/img/journaux/19_journal_2_3/19_journal_2_3.png" >> /tmp/journaux
	fi
	menu_reception
}

function affichageMail_envois()
{
	numero=$1 #numero du mail a afficher

	clear
	e_header "AFFICHAGE DU MAIL #$numero"
	echo "==========================================="
	echo

	# Affiche le mail 
	if [ $numero == "1" ]; then
		nomFichier=$ESCAPE_RES/img/mail/envoi/emailBoiteEnvoi.png
		echo "Affichage du mail"
		sleep 0.5
		eog $nomFichier &
		sleep 1
		eog $ESCAPE_RES/img/mail/envoi/journal/19_journal_2_2_1.png &
		echo "2;19_Journal_2.2.1;$ESCAPE_RES/img/journaux/19_journal_2_2_1/19_journal_2_2_1.png" >> /tmp/journaux
	fi

	#cat $nomFichier
	user_wait_input "Appuyez sur une touche pour revenir au menu precedent"; if is_confirmed; then menu_envois; fi
	menu_envois
}


function menu_envois()
{
	clear
	e_header "BOITE D'ENVOIS"
	# Affiche une liste de mail 
	cat $listeMail_envois
	echo "==========================================="
	echo
	echo "q: Quitter cet ecran et revenir au precedent"
	echo
	echo -n "Faites un choix : "
	read choix
	
	if [ "$choix" == "1" ] ; then
		affichageMail_envois 1
	#elif [ "$choix" == "2" ] ; then
		#affichageMail_envois 2
	#elif [ "$choix" == "3" ] ; then
		#affichageMail_envois 3
	#elif [ "$choix" == "4" ] ; then
		#affichageMail_envois 4
	#elif [ "$choix" == "5" ] ; then
		#affichageMail_envois 5
	
	elif [ "$choix" == "q" ] ; then
		menu_mail

	else
		echo
		echo -n $(e_warning "Veuillez selectionner un des choix du menu.")
		sleep $ESCAPE_SLEEPTIME_M
		menu_envois
	fi

}

main
